### ISSUE TITLE
Non-strict parsing when there are competing 'perfect' and 'imperfect' stacks sometimes picks the wrong one

### ISSUE THREAD

**Issue by afri** [lezer-parser/lezer#12]
I've been looking into the reason for the failing tests in lezer-parser/javascript when parsing non-strict (https://github.com/lezer-parser/javascript/issues/1#issue-545532293).

It looks like the problem is that imperfect stacks eventually end up with a perfect (`badness==0`) score if a sufficient number of tokens have been shifted. So at the end of parsing you have 'imperfect' stacks competing with a 'perfect' stack.

Here's a proposed fix:
At https://github.com/lezer-parser/lezer/blob/master/src/stack.ts#L199, change:
```
if (nextEnd > this.pos)
        this.badness = (this.badness >> 1) + (this.badness >> 2) // (* 0.75)
```
to something like:
```
if (nextEnd > this.pos && this.badness > 0)
        this.badness = Math.max(1, (this.badness >> 1) + (this.badness >> 2)) // (* 0.75)
```
This fixes the lezer-parser/javascript tests when forcing non-strict parsing.

**Comment by afri** [comment]
Actually... while the above fix will correctly prioritize 'perfect' over 'imperfect' stacks, it still leads to all imperfect stacks ending up with the same badness (=1) given a sufficient number of shifts. 

The result is that lezer often picks an objectively worse parsing. 

In my testing with the js parser this is fixed by replacing the integer arithmetic and letting `badness` converge asymptotically towards 0:
```
if (nextEnd > this.pos)
  this.badness *= 0.75;
```

**Comment by marijnh** [comment]
I've been trying to attack this as well for the past few days, but with not much luck either. Patch b19148f7b90 makes it slightly less common by making badness scores bigger, allowing them to stick around longer, but that still leaves a few failing tests.

In general, the problem is that recovery is happening at all when there is another parse that can move along without errors. The way stacks are advanced independently makes it hard to tell whether this is the case. I've been trying to frame the way multiple active stacks are handled to make it easier to reason about, but the process has so many constraints that I've not been making much progress.

**Comment by marijnh** [comment]
One thing that might help is to give up on having just one badness score, and track both number of recoveries and number of successful shifts since the last recovery (which I believe is what tree-sitter does).

**Comment by marijnh** [comment]
Renamed this issue, merging lezer-parser/javascript#1 into it.

**Comment by marijnh** [comment]
In short, what happens is that (explicit) ambiguities in the grammar can cause dead-end parses even in perfectly valid input, which will currently cause recovery to happen. If the parse goes on long enough and the recovery stacks aren't pruned, they'll converge back to badness=0, and run the risk of being accepted as the final parse, even though they contain unnecessary error recovery nodes.

**Comment by marijnh** [comment]
Patch 6e29df60ac6db addresses this by splitting the heap of stacks kept by a parse context into regular and stopped ones. All regular ones at a given position get to advance first. When a stack can't advance normally, it is put on the stopped heap. When no more regular parses are available for a position, the stopped parses are looked at. At this point, they can tell when to avoid recovering at all because there are better stacks available.
