### ISSUE TITLE
Markdown Grammar

### ISSUE THREAD

**Issue by curran** [lezer-parser/lezer#20]
It would be great to add a new [grammar](https://lezer.codemirror.net/#grammars) for Markdown.

Related: https://github.com/codemirror/codemirror.next/issues/158

**Comment by marijnh** [comment]
It might be possible to use Lezer to parse Markdown, but it's going to be very awkward, since Markdown is structured in a fundamentally different way than the type of context-free grammars that Lezer is meant for. I'd welcome someone taking a shot at this, but I am definitely not going to work on it myself, so I'll close this.
