### ISSUE TITLE
export parser.term.js

### ISSUE THREAD

**Issue by Nexucis** [lezer-parser/lezer#28]
Would you be agree to include in the index.es.js the exported const you can find in the file `parser.term.js` ?

If we assume for the example, I have the following file `parser.term.js`:

```javascript
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  MyNodeName = 1,
```

Then instead of doing this: 

```typescript
tree.name === "MyNodeName"
```

We could do this : 

```typescript
import { MyNodeName } from 'my-lezer-grammar'

[...]

tree.type.id === MyNodeName 
```

Like that it avoid any string duplication.

**Comment by marijnh** [comment]
No, that is intentionally not done, because it'd add a lot of extra exports that are usually not going to be used. You could create your own wrapping script that re-exports the parser from the main script + the constants you need from the terms script, and run Rollup on that to produce your output module file.
